import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:echat/Advisor%20View/advice_model.dart';
import 'package:echat/User%20Credential/userfirestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';

class PostAdviceScreen extends StatefulWidget {
  const PostAdviceScreen({super.key});

  @override
  State<PostAdviceScreen> createState() => _PostAdviceScreenState();
}

class _PostAdviceScreenState extends State<PostAdviceScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _contentController = TextEditingController();
  String _selectedCategory = 'Crop Care';
  bool _isLoading = false;

  final List<String> _categories = [
    'Crop Care',
    'Animal Health',
    'Market Tips',
    'Weather & Climate',
    'Equipment & Tech',
    'General',
  ];

  Future<void> _submitAdvice() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final user = FirebaseAuth.instance.currentUser;
      if (user == null) throw Exception("User not logged in");

      // Fetch user details for author name
      final userData = await UserRepository().getUser(user.uid);
      final authorName = userData?.fullName ?? "Expert Advisor";

      final advice = AdviceModel(
        id: '', // Generated by Firestore
        title: _titleController.text.trim(),
        content: _contentController.text.trim(),
        authorId: user.uid,
        authorName: authorName,
        category: _selectedCategory,
        timestamp: DateTime.now(),
      );

      await FirebaseFirestore.instance.collection('advice_posts').add(advice.toMap());

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text("Advice posted successfully!")),
        );
        Navigator.pop(context); // Return to Dashboard
      }
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text("Error posting advice: $e")),
      );
    } finally {
      setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Post New Advice"),
        backgroundColor: Colors.teal[700],
        foregroundColor: Colors.white,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Title
              TextFormField(
                controller: _titleController,
                decoration: InputDecoration(
                  labelText: "Title",
                  hintText: "e.g., Best Practices for Maize Harvest",
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
                  filled: true,
                  fillColor: Colors.grey[50],
                ),
                validator: (val) => val!.isEmpty ? "Title is required" : null,
              ),
              const SizedBox(height: 20),

              // Category Dropdown
              DropdownButtonFormField<String>(
                value: _selectedCategory,
                decoration: InputDecoration(
                  labelText: "Category",
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
                  filled: true,
                  fillColor: Colors.grey[50],
                ),
                items: _categories.map((cat) {
                  return DropdownMenuItem(value: cat, child: Text(cat));
                }).toList(),
                onChanged: (val) => setState(() => _selectedCategory = val!),
              ),
              const SizedBox(height: 20),

              // Content Body
              TextFormField(
                controller: _contentController,
                decoration: InputDecoration(
                  labelText: "Content",
                  hintText: "Write your detailed advice here...",
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
                  filled: true,
                  fillColor: Colors.grey[50],
                  alignLabelWithHint: true,
                ),
                maxLines: 10,
                validator: (val) => val!.isEmpty ? "Content is required" : null,
              ),
              const SizedBox(height: 30),

              // Submit Button
              SizedBox(
                height: 50,
                child: ElevatedButton(
                  onPressed: _isLoading ? null : _submitAdvice,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.teal,
                    foregroundColor: Colors.white,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                  ),
                  child: _isLoading
                      ? const CircularProgressIndicator(color: Colors.white)
                      : const Text("Publish Advice", style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
