// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_u-CbOyvERFhtNl9dTHSOsNCsTV9TMgc',
    appId: '1:447095155412:web:656a232313e4f5ed5ba941',
    messagingSenderId: '447095155412',
    projectId: 'eyyosi',
    authDomain: 'eyyosi.firebaseapp.com',
    databaseURL: 'https://eyyosi-default-rtdb.firebaseio.com',
    storageBucket: 'eyyosi.firebasestorage.app',
    measurementId: 'G-LF6J4ZMH2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDE653zWiA2ltlG6jOYdUkIOJNTAx3p70',
    appId: '1:447095155412:android:093b96e347d4bb545ba941',
    messagingSenderId: '447095155412',
    projectId: 'eyyosi',
    databaseURL: 'https://eyyosi-default-rtdb.firebaseio.com',
    storageBucket: 'eyyosi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzMWbMD6LtUudZ0k1MuukrPv6I4T0OAlM',
    appId: '1:447095155412:ios:126c5cb357456feb5ba941',
    messagingSenderId: '447095155412',
    projectId: 'eyyosi',
    databaseURL: 'https://eyyosi-default-rtdb.firebaseio.com',
    storageBucket: 'eyyosi.firebasestorage.app',
    iosBundleId: 'com.example.echat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzMWbMD6LtUudZ0k1MuukrPv6I4T0OAlM',
    appId: '1:447095155412:ios:126c5cb357456feb5ba941',
    messagingSenderId: '447095155412',
    projectId: 'eyyosi',
    databaseURL: 'https://eyyosi-default-rtdb.firebaseio.com',
    storageBucket: 'eyyosi.firebasestorage.app',
    iosBundleId: 'com.example.echat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_u-CbOyvERFhtNl9dTHSOsNCsTV9TMgc',
    appId: '1:447095155412:web:e82e34ab396a52d45ba941',
    messagingSenderId: '447095155412',
    projectId: 'eyyosi',
    authDomain: 'eyyosi.firebaseapp.com',
    databaseURL: 'https://eyyosi-default-rtdb.firebaseio.com',
    storageBucket: 'eyyosi.firebasestorage.app',
    measurementId: 'G-NC93XLKXFB',
  );
}
